"""Generate private advisory files (NOT public posts) for repos with confirmed vulns.

IMPORTANT — Responsible Disclosure:
    Security vulnerabilities MUST be reported PRIVATELY via GitHub Security
    Advisories. This tool generates advisory files for MANUAL submission.
    NEVER post security findings as public GitHub Issues.
"""
import json
from pathlib import Path

data = json.load(open(r"c:\Users\matth\OneDrive\Desktop\ansede-static-focus\tmp\triage\triage_results_20260521_110614.json", encoding="utf-8"))
confirmed = [f for f in data["findings"] if f.get("verdict") == "confirmed"]

by_repo = {}
for f in confirmed:
    repo = f.get("repo_id", "unknown")
    by_repo.setdefault(repo, []).append(f)

out_dir = Path(r"c:\Users\matth\OneDrive\Desktop\ansede-static-focus\tmp\disclosure")
out_dir.mkdir(parents=True, exist_ok=True)

for repo, findings in sorted(by_repo.items()):
    # Group by severity
    by_sev = {"critical": [], "high": [], "medium": [], "low": []}
    for f in findings:
        sev = f.get("severity", "medium").lower()
        by_sev.setdefault(sev, []).append(f)

    lines = [
        f"# Security Findings — {repo}",
        "",
        f"Hi {repo.split('/')[0] if '/' in repo else 'maintainers'}!",
        "",
        "An automated scan of this repository using **ansede-static** (a free, open-source, zero-dependency SAST engine scanning 8 languages) identified the following potential security vulnerabilities:",
        "",
        "---",
        "",
        "## Summary",
        "",
        f"| Severity | Count |",
        "|----------|-------|",
    ]
    total_confirmed = len(findings)
    for sev in ("critical", "high", "medium", "low"):
        c = len(by_sev.get(sev, []))
        if c > 0:
            lines.append(f"| {sev.capitalize()} | {c} |")

    lines.extend([
        "",
        "## Findings",
        "",
    ])
    for i, f in enumerate(findings, 1):
        cwe = f.get("cwe", "?")
        severity = f.get("severity", "?").upper()
        filepath = f.get("file", "?")
        # Strip local machine prefix for privacy
        for prefix in [r"c:\Users\matth\OneDrive\Desktop\ansede-static-focus\tmp\clones\\",
                        r"c:\Users\matth\OneDrive\Desktop\ansede-static-focus\tmp\clones\\",
                        "/tmp/", "/home/"]:
            if filepath.startswith(prefix):
                filepath = filepath[len(prefix):]
                break
        lines.extend([
            f"### {i}. {f.get('title', '?')}",
            "",
            f"| Detail | Value |",
            f"|--------|-------|",
            f"| **Rule** | `{f.get('rule_id', '?')}` |",
            f"| **CWE** | {cwe} |",
            f"| **Severity** | {severity} |",
            f"| **Confidence** | {f.get('confidence', 0):.2f} |",
            f"| **File** | `{filepath}:{f.get('line', '?')}` |",
            f"| **Analysis** | {f.get('analysis_kind', '?')} |",
            "",
            f"**Description:** {f.get('title', '?')}",
            "",
            f"**Recommendation:** {f.get('suggestion', 'N/A')}",
            "",
            "---",
            "",
        ])

    lines.extend([
        "## About ansede-static",
        "",
        "**ansede-static** is a free, open-source, zero-dependency SAST engine that scans code for security vulnerabilities across **7 languages** (Python, JavaScript, TypeScript, Java, C#, Go, Ruby, PHP).",
        "",
        "- **GitHub:** https://github.com/mattybellx/ansede",
        "- **PyPI:** `pip install ansede-static`",
        "- **VS Code Extension:** Available on marketplace",
        "",
        "To reproduce: `pip install ansede-static && ansede-static /path/to/repo`",
        "",
        "---",
        "",
        "*This is an automated responsible disclosure notification generated by ansede-static v2.3.0-dev. "
        "Please review the findings above at your earliest convenience.*",
    ])

    content = "\n".join(lines)
    safe_name = repo.replace("/", "_").replace(" ", "_")
    path = out_dir / f"discussion_{safe_name}.md"
    path.write_text(content, encoding="utf-8")
    print(f"  ✅ {path.name} — {total_confirmed} findings")

print(f"\nDone! {len(by_repo)} discussion posts generated in {out_dir}/")
print("To post, copy the markdown to each repo's GitHub Discussions tab.")
